
#' Generate palette suitable for coloring a set
#'
#' Takes a simple palette and expands / oscillates
#' it for use with Mandelbrot sets.
#'
#' @param palette vector of colour hex strings (e.g. '#FFFFFF')
#' @param in_set colour for areas in the Mandelbrot set
#'
#' @examples
#' view <- mandelbrot(xlim = c(-0.8438146, -0.8226294),
#'   ylim = c(0.1963144, 0.2174996), iter = 500)
#'
#' blues <- RColorBrewer::brewer.pal(9, "Blues")
#' cols <- mandelbrot_palette(blues, in_set = "white")
#' image(log(view$z), col = cols, axes = FALSE)
#'
#' spectral <- RColorBrewer::brewer.pal(11, "Spectral")
#' cols <- mandelbrot_palette(spectral)
#' image(-1/view$z, col = cols, axes = FALSE)
#'
#' @export
mandelbrot_palette <- function(palette, folds = 2, in_set = "black") {
  if (length(palette) < 50) {
    palette <- colorRampPalette(palette)(50)
  }
  c(rep(c(palette, rev(palette)), folds), in_set)
}

#' Plot a Mandelbrot set using base graphics
#'
#' Draws coloured set membership using \code{image}.
#'
#' @param mandelbrot an object generated by \code{\link[mandelbrot]{mandelbrot}}
#'
#' @export
plot.mandelbrot <- function(mandelbrot,
  col = mandelbrot_palette(c("white", grey.colors(50))),
  transform = c("none", "inverse", "log"), ...) {

  transform <- match.arg(transform)
  old_par <- par()

  par(mar = rep(1, 4))

  if (transform != "none") {
    if (transform == "inverse") {
      mandelbrot$z <- 1/mandelbrot$z
    } else {
      if (transform == "log") {
        mandelbrot$z <- log(mandelbrot$z)
      } else {
        stop("transform not recognised: ", transform)
      }
    }
  }

  image(mandelbrot, col = col, axes = FALSE, ...)

  par <- old_par
}

#' @export
print.mandelbrot <- function(x, ...) {
  cat(" Mandelbrot set view object within limits x:",
    paste(range(x$x), collapse = ", "),
    "and y:",
    paste(range(x$y), collapse = ", "),
    "\n")
  cat(" Iterations matrix:",
    paste(dim(x$z), collapse = " x "))

   invisible(x)
}

#' Convert Mandelbrot object to data.frame for plotting
#'
#' Converts objects produced by \code{\link[mandelbrot]{mandelbrot}}
#' to tidy data.frames for use with ggplot and other tidyverse packages.
#'
#' @param mandelbrot a Mandelbrot set object produced by \code{\link[mandelbrot]{mandelbrot}}
#'
#' @return a 3-column \code{data.frame}
#'
#' @examples
#'
#' mb <- mandelbrot()
#' df <- as.data.frame(mb)
#' head(df)
#'
#' @export
as.data.frame.mandelbrot <- function(mandelbrot) {
  #df <- reshape2::melt(mandelbrot$z)
  df <- data.table::melt(mandelbrot$z)
  df$x <- mandelbrot$x[df$Var1]
  df$y <- mandelbrot$y[df$Var2]
  df[,c("x", "y", "value")]
}


expand.grid.jc <- function(seq1, seq2) {
  cbind(Var1 = rep.int(seq1, length(seq2)),
    Var2 = rep.int(seq2, rep.int(length(seq1), length(seq2))))
}
